---
- hosts: 
  become: yes
  tasks:      
    - name: "Download compose"
      command: curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-Linux-x86_64" -o /usr/local/bin/docker-compose
    - name: "Chmod compose"
      command: chmod +x /usr/local/bin/docker-compose
    - name: "Create a symbolic link compose "
      command: ln -s /usr/local/bin/docker-compose /usr/bin/docker-compose
